version: '3.8'

services:
  mastodon-telegram:
    build: .
    container_name: mastodon-telegram-bridge
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Mount a volume for the database to persist data
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlite3; sqlite3.connect('/app/data/synced_posts.db').close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
